# App name
spring.application.name=orderapp
server.port=8081

# JPA settings ? safe, no secrets here
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Active profile ? tells Spring to also load application-local.properties
spring.profiles.active=local

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true